language: python
python:
  - '3.6'

stages:
  - test
  - name: deploy
    if: "(tag IS present) AND (repo = ridi/django-shard-library)"

jobs:
  include:
  - stage: test
    before_script: make install-dev
    script: make test
  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      user: ridi
      password:
        secure: "EK0QAzExQsMWqltJGiPpo7r73owqZIfCSzk/erxxoVlJ+cmcwFlAvSPbI0qm9NutXwC3yAwuEEc+ifOR9fQMqNPqN5hjJ6LWKSmglVEcqEDTmTu18ZbQrB5NAIwdlq7A8Tj2KjERjOtmxHJdGszapR34KXW6Om66uT7ssskdgRhKrjY/lL/hp0GUKbwjTDQhnhi9oDuxRmkZOZy06gP2x4Sa+FpUsKQCTJp6O8K28BFKAOq47ThsAQYK+NWJ3IE659z9JCcK2PMt0Kuu4j1JX0YIJBD6yn8nWstW8EWEIJ1bpX13SDavSO5zS6Po/OucaurR7miCNqrctmv4LgSYP35zVmjFbKza9A59KzDcghEl94ourd+d22GLecf2v4XPj3/pVeI/HBTyC5P2ZdOlkLmGJ+NEdtMSrvSLVqljUZMxy2pw2jdBt+SawvCQkyrCzdeOlNniagIPSsLyMkTV9q6cLiISYNcGTucddxTJeSlsQa/wbe0VqJyV9b/lzCzElPj6ec9atpIwRNZwlp9Pf7b76Pexz2w9k63LC5pOFYxsgCAsJZ6NdB1UW+KF2BR3AkjBgDWnSitiIG2D21OyIUasPZXVm+i23oACXBZ8U9M5Z0TFXve3AVCymVx/DcrXc1vMYZf86QPPKLwNYlctZPmriA6JTHWpfbRfUQtYC1o="
      on:
        repo: ridi/django-shard-library
        tags: true
