# Generated by Django 2.0.2 on 2018-05-28 05:40

from django.db import migrations, models
import shard_static.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticTransmitStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_model_key', models.CharField(max_length=64, unique=True, verbose_name='Static Model Key')),
                ('criterion_datetime', models.DateTimeField(default=shard_static.models.get_first_day, verbose_name='Criterion Datetime')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'db_table': 'static_transmit_status',
            },
        ),
    ]
