# Generated by Django 2.0.2 on 2018-04-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shard_static', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shardsyncstatus',
            name='last_locked_time',
            field=models.DateTimeField(null=True, verbose_name='Last Locked Time'),
        ),
    ]
