# Generated by Django 2.0.2 on 2018-05-24 03:45

from django.db import migrations, models
import django.utils.timezone
import shard_static.models


class Migration(migrations.Migration):

    dependencies = [
        ('shard_static', '0002_auto_20180515_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticsyncstatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticsyncstatus',
            name='criterion_datetime',
            field=models.DateTimeField(default=shard_static.models.get_first_day, verbose_name='Criterion Datetime'),
        ),
        migrations.AlterField(
            model_name='staticsyncstatus',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
    ]
