# Generated by Django 2.0.2 on 2018-04-09 06:44

from django.db import migrations, models
import shard.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticSyncStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_model_key', models.CharField(max_length=64, verbose_name='Static Model Key')),
                ('last_modified', models.DateTimeField(null=True, verbose_name='Last Modified')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Is Locked')),
                ('last_locked_time', models.DateTimeField(null=True, verbose_name='Last Locked Time')),
            ],
            options={
                'db_table': 'shard_sync_status',
            },
            bases=(shard.mixins.ShardStaticMixin, models.Model),
        ),
    ]
