# Generated by Django 2.0.2 on 2018-04-09 09:47

from django.db import migrations, models
import django.db.models.deletion
import shard.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.NormalModel')),
            ],
        ),
        migrations.CreateModel(
            name='ShardModelA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='유저 idx')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.ShardModelA')),
            ],
            bases=(shard.mixins.ShardMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ShardModelB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='유저 idx')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.ShardModelA')),
            ],
            bases=(shard.mixins.ShardMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ShardStaticA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(shard.mixins.ShardStaticMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ShardStaticAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(shard.mixins.ShardStaticMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ShardStaticB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(shard.mixins.ShardStaticMixin, models.Model),
        ),
        migrations.AddField(
            model_name='shardmodela',
            name='static_all',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.ShardStaticAll'),
        ),
        migrations.AddField(
            model_name='shardmodela',
            name='static_other',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.ShardStaticB'),
        ),
        migrations.AddField(
            model_name='shardmodela',
            name='static_same',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.ShardStaticA'),
        ),
        migrations.AddField(
            model_name='normalmodel',
            name='shard_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.ShardModelA'),
        ),
        migrations.AddField(
            model_name='normalmodel',
            name='static_all',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.ShardStaticAll'),
        ),
    ]
