# Generated by Django 2.0.2 on 2018-04-10 08:28

from django.db import migrations, models
import shard.fields
import shard.mixins
import shard.strategy.id_generation.table
import shard.strategy.id_generation.uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdGenerateTestModel',
            fields=[
                ('id', shard.fields.TableStrategyPkField(primary_key=True, serialize=False, source_model='TestIds', strategy=shard.strategy.id_generation.table.TableStrategy(source_model='TestIds'))),
            ],
        ),
        migrations.CreateModel(
            name='TestIds',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(shard.mixins.SpecificDatabaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UUIDTestModel',
            fields=[
                ('id', shard.fields.UUID4StrategyPkField(max_length=32, primary_key=True, serialize=False, strategy=shard.strategy.id_generation.uuid.UUIDStrategy(), verbose_name='UUID Pk field')),
            ],
        ),
    ]
