# Generated by Django 2.0.2 on 2018-04-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalmodel',
            name='normal_parent',
        ),
        migrations.RemoveField(
            model_name='normalmodel',
            name='static_all',
        ),
        migrations.RemoveField(
            model_name='shardmodela',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='shardmodela',
            name='static_all',
        ),
        migrations.RemoveField(
            model_name='shardmodela',
            name='static_same',
        ),
    ]
