# Generated by Django 2.0.2 on 2018-05-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20180502_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shardstatica',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='shardstaticall',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='shardstaticb',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modified'),
        ),
    ]
